# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-24 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170423_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterylevel',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batterytemperature',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
