# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-24 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170424_0650'),
    ]

    operations = [
    
    ]
