# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-28 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170428_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemInfoFreeRam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MemInfoTotalRam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MemInfoUsedRam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('value', models.IntegerField()),
            ],
        )    ]
