# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-28 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170428_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnum', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=500)),
            ],
        )
    ]
